blank_issues_enabled: false
contact_links:
  - name: OxidNG Procedural issues
    url: https://github.com/GFW-knocker/Xray-core
    about: If you have a question about Xray instead of OxidNG, please go to this link to discuss.
